- hosts: 127.0.0.1
  connection: local
  tasks:
      - name: Check If Spotify Repository Exists
        stat:
            path: /etc/apt/sources.list.d/spotify.list
        register: spotify_repo_file

        # only add spotify repo when it does not exist already
      - name: Add Spotify Repository
        when: not spotify_repo_file.exists
        ignore_errors: True
        become: yes
        become_user: root
        local_action: command sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 && echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list 



      - name: Install Apt-Packages
        become: yes
        become_user: root
        apt:
            name: "{{ packages }}"
        vars:
            packages:
                - htop
                - vim
                - tmux
                - i3
                - curl
                - git
                - spotify-client
                - xclip
                - dunst
                - libnotify-bin # for notify-send command
                - redshift
                - sxiv

      # Installing OhMyZsh
      # check if zsh is already installed            
      - name: Is OhMyZsh installed
        local_action: command ./installed zsh
        register: zsh_installed
        ignore_errors: True

      - name: Install OhMyZsh
        local_action: command sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        when: zsh_installed is failed
                            
        # Setup dotfile links
      - name: Create dotfile links
        local_action: command ./create_links.sh

      - name: "setup ~/.config folder"
        local_action: command cp -r .config/. ~/.config/
        
      - name: "setup ~/.scripts folder"
        local_action: command perl setup_scripts.pl

